import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from datetime import date
fun mailSender():
      #todays date
      today = date.today()

      # Define the sender's and receiver's email addresses
      sender = 'ahmadme.jamia@gmail.com'
      receiver = 'rayeen.saif@gmail.com'

      # Define the email message and attach the file
      subject = 'Automatic attendance mail' + str(today)
      body = 'here is today\'s attendance sheet, Auto generated by facial recognition system'
      file_path = 'Attendance.csv'

      # Create a multipart message object and add the email components to it
      message = MIMEMultipart()
      message['From'] = sender
      message['To'] = receiver
      message['Subject'] = subject

      # Add the body of the email
      message.attach(MIMEText(body, 'plain'))

      # Add the attachment to the email
      with open(file_path, 'rb') as attachment:
          part = MIMEApplication(attachment.read(), _subtype='csv')
          part.add_header('Content-Disposition', f'attachment; filename="{file_path}"')
          message.attach(part)

      # Define the SMTP server and login credentials
      smtp_server = 'smtp.gmail.com'
      username = 'ahmadme.jamia@gmail.com'
      password = 'tgvwjvhzipdteran'

      # Create a secure SSL connection to the SMTP server and send the email
      with smtplib.SMTP_SSL(smtp_server, 465) as smtp:
          smtp.login(username, password)
          smtp.sendmail(sender, receiver, message.as_string())

      print('Email sent!')
